DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'SAUCES';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE SAUCES CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE SAUCES(
sc_id NUMBER(10),
price NUMBER(10),
title VARCHAR2(50 CHAR) CONSTRAINT sc_title_nn NOT NULL,
description VARCHAR2(200 CHAR),
CONSTRAINT sc_id_pk PRIMARY KEY (sc_id))';

nCount:=0;--sequence and trigger for primary key
SELECT COUNT(*)
  INTO nCount
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'SC_SEQ';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SC_SEQ';
END IF;

EXECUTE IMMEDIATE 'CREATE SEQUENCE SC_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE';

EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER sc_id_trg
BEFORE INSERT ON sauces
FOR EACH ROW
BEGIN
  IF :new.sc_id IS NULL THEN
    SELECT sc_seq.nextval INTO :new.sc_id FROM dual;
  END IF;
END;';
END;
/

DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'DRINKS';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE DRINKS CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE DRINKS(
drnk_id NUMBER(10),
volume NUMBER(10),
price NUMBER(10),
title VARCHAR2(50 CHAR) CONSTRAINT drnk_title_nn NOT NULL,
description VARCHAR2(200 CHAR),
CONSTRAINT drnk_id_pk PRIMARY KEY (drnk_id))';

nCount:=0;--sequence and trigger for primary key
SELECT COUNT(*)
  INTO nCount
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'DRNK_SEQ';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP SEQUENCE DRNK_SEQ';
END IF;

EXECUTE IMMEDIATE 'CREATE SEQUENCE DRNK_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE';

EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER drnk_id_trg
BEFORE INSERT ON drinks
FOR EACH ROW
BEGIN
  IF :new.drnk_id IS NULL THEN
    SELECT drnk_seq.nextval INTO :new.drnk_id FROM dual;
  END IF;
END;';
END;
/

DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'INGREDIENTS';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE INGREDIENTS CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE INGREDIENTS(
ingrd_id NUMBER(10),
title VARCHAR2(50 CHAR) CONSTRAINT ingrd_title_nn NOT NULL,
description VARCHAR2(200 CHAR),
CONSTRAINT ingrd_id_pk PRIMARY KEY (ingrd_id))';

nCount:=0;--sequence and trigger for primary key
SELECT COUNT(*)
  INTO nCount
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'INGRD_SEQ';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP SEQUENCE INGRD_SEQ';
END IF;

EXECUTE IMMEDIATE 'CREATE SEQUENCE INGRD_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE';

EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER ingrd_id_trg
BEFORE INSERT ON ingredients
FOR EACH ROW
BEGIN
  IF :new.ingrd_id IS NULL THEN
    SELECT ingrd_seq.nextval INTO :new.ingrd_id FROM dual;
  END IF;
END;';
END;
/

DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'PIZZAS';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE PIZZAS CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE PIZZAS(
pz_id NUMBER(10),
title VARCHAR2(50 CHAR) CONSTRAINT pz_title_nn NOT NULL,
type VARCHAR2(50 CHAR),
weight NUMBER(10),
price NUMBER(10),
description VARCHAR2(200 CHAR),
CONSTRAINT pz_id_pk PRIMARY KEY (pz_id))';

nCount:=0;--sequence and trigger for primary key
SELECT COUNT(*)
  INTO nCount
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'PZ_SEQ';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP SEQUENCE PZ_SEQ';
END IF;

EXECUTE IMMEDIATE 'CREATE SEQUENCE PZ_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE';

EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER pz_id_trg
BEFORE INSERT ON pizzas
FOR EACH ROW
BEGIN
  IF :new.pz_id IS NULL THEN
    SELECT pz_seq.nextval INTO :new.pz_id FROM dual;
  END IF;
END;';
END;
/

DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'MEASUREMENT_UNITS';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE MEASUREMENT_UNITS CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE MEASUREMENT_UNITS(
msru_id NUMBER(10),
title VARCHAR2(100 CHAR),
CONSTRAINT msru_id_pk PRIMARY KEY (msru_id))';

nCount:=0;--sequence and trigger for primary key
SELECT COUNT(*)
  INTO nCount
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'MSRU_SEQ';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP SEQUENCE MSRU_SEQ';
END IF;

EXECUTE IMMEDIATE 'CREATE SEQUENCE MSRU_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE';

EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER msru_id_trg
BEFORE INSERT ON measurement_units
FOR EACH ROW
BEGIN
  IF :new.msru_id IS NULL THEN
    SELECT msru_seq.nextval INTO :new.msru_id FROM dual;
  END IF;
END;';
END;
/

DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'PIZZAS_INGREDIENTS';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE PIZZAS_INGREDIENTS CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE PIZZAS_INGREDIENTS(
pz_pz_id NUMBER(10),
ingrd_ingrd_id NUMBER(10),
amount NUMBER(10),
msru_msru_id NUMBER(10),
CONSTRAINT pz_ingrd_pz_id_fk FOREIGN KEY (pz_pz_id)
REFERENCES PIZZAS (pz_id) ON DELETE CASCADE,
CONSTRAINT pz_ingrd_ingrd_id_fk FOREIGN KEY (ingrd_ingrd_id)
REFERENCES INGREDIENTS (ingrd_id) ON DELETE CASCADE,
CONSTRAINT pz_ingrd_msru_id_fk FOREIGN KEY (msru_msru_id)
REFERENCES MEASUREMENT_UNITS (msru_id) ON DELETE CASCADE)';
END;
/

DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'CLIENTS';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE CLIENTS CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE CLIENTS(
clnt_id NUMBER(10),
name VARCHAR2(100 CHAR),
address VARCHAR2(200 CHAR),
phone_number VARCHAR2(20),
CONSTRAINT clnt_id_pk PRIMARY KEY (clnt_id))';

nCount:=0;--sequence and trigger for primary key
SELECT COUNT(*)
  INTO nCount
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'CLNT_SEQ';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP SEQUENCE CLNT_SEQ';
END IF;

EXECUTE IMMEDIATE 'CREATE SEQUENCE CLNT_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE';

EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER clnt_id_trg
BEFORE INSERT ON clients
FOR EACH ROW
BEGIN
  IF :new.clnt_id IS NULL THEN
    SELECT clnt_seq.nextval INTO :new.clnt_id FROM dual;
  END IF;
END;';
END;
/

DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'ORDERS';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE ORDERS(
ord_id NUMBER(10),
clnt_clnt_id NUMBER(10),
order_date DATE,
delivery_date DATE,
description VARCHAR2(200 CHAR),
CONSTRAINT ord_id_pk PRIMARY KEY (ord_id),
CONSTRAINT ord_clnt_id_fk FOREIGN KEY (clnt_clnt_id)
REFERENCES CLIENTS (clnt_id) ON DELETE CASCADE)';

nCount:=0;--sequence and trigger for primary key
SELECT COUNT(*)
  INTO nCount
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'ORD_SEQ';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP SEQUENCE ORD_SEQ';
END IF;

EXECUTE IMMEDIATE 'CREATE SEQUENCE ORD_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE';

EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER ord_id_trg
BEFORE INSERT ON orders
FOR EACH ROW
BEGIN
  IF :new.ord_id IS NULL THEN
    SELECT ord_seq.nextval INTO :new.ord_id FROM dual;
  END IF;
END;';
END;
/

DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'ORDERS_PIZZAS';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS_PIZZAS CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE ORDERS_PIZZAS(
ord_ord_id NUMBER(10),
pz_pz_id NUMBER(10),
amount NUMBER(10),
CONSTRAINT ord_pz_ord_id_fk FOREIGN KEY (ord_ord_id)
REFERENCES ORDERS (ord_id) ON DELETE CASCADE,
CONSTRAINT ord_pz_pz_id_fk FOREIGN KEY (pz_pz_id)
REFERENCES PIZZAS (pz_id) ON DELETE CASCADE)';
END;
/

DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'ORDERS_DRINKS';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS_DRINKS CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE ORDERS_DRINKS(
ord_ord_id NUMBER(10),
drnk_drnk_id NUMBER(10),
amount NUMBER(10),
CONSTRAINT ord_drnk_ord_id_fk FOREIGN KEY (ord_ord_id)
REFERENCES ORDERS (ord_id) ON DELETE CASCADE,
CONSTRAINT ord_drnk_drnk_id_fk FOREIGN KEY (drnk_drnk_id)
REFERENCES DRINKS (drnk_id) ON DELETE CASCADE)';
END;
/

DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'ORDERS_SAUCES';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS_SAUCES CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE ORDERS_SAUCES(
ord_ord_id NUMBER(10),
sc_sc_id NUMBER(10),
amount NUMBER(10),
CONSTRAINT ord_sc_ord_id_fk FOREIGN KEY (ord_ord_id)
REFERENCES ORDERS (ord_id) ON DELETE CASCADE,
CONSTRAINT ord_sc_sc_id_fk FOREIGN KEY (sc_sc_id)
REFERENCES SAUCES (sc_id) ON DELETE CASCADE)';
END;
/