PROMPT clients...
DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'CLIENTS';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE CLIENTS CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE CLIENTS(
clnt_id NUMBER(5),
name VARCHAR2(100 CHAR),
address VARCHAR2(200 CHAR),
home VARCHAR2(100 CHAR),
appartment VARCHAR2(100 CHAR),
phone_number VARCHAR2(20),
comments VARCHAR2(200 CHAR),
CONSTRAINT clnt_id_pk PRIMARY KEY (clnt_id))';

nCount:=0;--sequence and trigger for primary key
SELECT COUNT(*)
  INTO nCount
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'CLNT_SEQ';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP SEQUENCE CLNT_SEQ';
END IF;

EXECUTE IMMEDIATE 'CREATE SEQUENCE CLNT_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE';

EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER clnt_id_trg
BEFORE INSERT ON clients
FOR EACH ROW
BEGIN
  IF :new.clnt_id IS NULL THEN
    SELECT clnt_seq.nextval INTO :new.clnt_id FROM dual;
  END IF;
END;';
END;
/
