PROMPT orders_drinks...
DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'ORDERS_DRINKS';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS_DRINKS CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE ORDERS_DRINKS(
ord_ord_id NUMBER(10),
drnk_drnk_id NUMBER(10),
amount NUMBER(10),
CONSTRAINT ord_drnk_ord_id_fk FOREIGN KEY (ord_ord_id)
REFERENCES ORDERS (ord_id) ON DELETE CASCADE,
CONSTRAINT ord_drnk_drnk_id_fk FOREIGN KEY (drnk_drnk_id)
REFERENCES DRINKS (drnk_id) ON DELETE CASCADE)';
END;
/