PROMPT orders_sauces...
DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'ORDERS_SAUCES';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS_SAUCES CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE ORDERS_SAUCES(
ord_ord_id NUMBER(10),
sc_sc_id NUMBER(10),
amount NUMBER(10),
CONSTRAINT ord_sc_ord_id_fk FOREIGN KEY (ord_ord_id)
REFERENCES ORDERS (ord_id) ON DELETE CASCADE,
CONSTRAINT ord_sc_sc_id_fk FOREIGN KEY (sc_sc_id)
REFERENCES SAUCES (sc_id) ON DELETE CASCADE)';
END;
/