PROMPT orders_pizzas...
DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'ORDERS_PIZZAS';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS_PIZZAS CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE ORDERS_PIZZAS(
ord_ord_id NUMBER(10),
pz_pz_id NUMBER(10),
amount NUMBER(10),
CONSTRAINT ord_pz_ord_id_fk FOREIGN KEY (ord_ord_id)
REFERENCES ORDERS (ord_id) ON DELETE CASCADE,
CONSTRAINT ord_pz_pz_id_fk FOREIGN KEY (pz_pz_id)
REFERENCES PIZZAS (pz_id) ON DELETE CASCADE)';
END;
/