PROMPT pizza_types...
DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'PIZZA_TYPES';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE PIZZA_TYPES CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE PIZZA_TYPES(
pztp_id NUMBER(10),
def VARCHAR2(50 CHAR),
CONSTRAINT pztp_id_pk PRIMARY KEY (pztp_id))';

nCount:=0;--sequence and trigger for primary key
SELECT COUNT(*)
  INTO nCount
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'PZTP_SEQ';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP SEQUENCE PZTP_SEQ';
END IF;

EXECUTE IMMEDIATE 'CREATE SEQUENCE PZTP_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE';

EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER pztp_id_trg
BEFORE INSERT ON pizza_types
FOR EACH ROW
BEGIN
  IF :new.pztp_id IS NULL THEN
    SELECT pztp_seq.nextval INTO :new.pztp_id FROM dual;
  END IF;
END;';
END;
/
