PROMPT pizzas...
DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'PIZZAS';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE PIZZAS CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE PIZZAS(
pz_id NUMBER(10),
def VARCHAR2(50 CHAR),
pztp_pztp_id NUMBER(10),
weight NUMBER(10),
price NUMBER(10),
comments VARCHAR2(200 CHAR),
CONSTRAINT pz_id_pk PRIMARY KEY (pz_id),
CONSTRAINT pz_pztp_id_fk FOREIGN KEY (pztp_pztp_id)
REFERENCES PIZZA_TYPES (pztp_id) ON DELETE CASCADE)';

nCount:=0;--sequence and trigger for primary key
SELECT COUNT(*)
  INTO nCount
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'PZ_SEQ';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP SEQUENCE PZ_SEQ';
END IF;

EXECUTE IMMEDIATE 'CREATE SEQUENCE PZ_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE';

EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER pz_id_trg
BEFORE INSERT ON pizzas
FOR EACH ROW
BEGIN
  IF :new.pz_id IS NULL THEN
    SELECT pz_seq.nextval INTO :new.pz_id FROM dual;
  END IF;
END;';
END;
/
