PROMPT sauces...
DECLARE --CREATE OR REPLACE
nCount NUMBER;
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'SAUCES';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE SAUCES CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE SAUCES(
sc_id NUMBER(10),
price NUMBER(10),
def VARCHAR2(50 CHAR) CONSTRAINT sc_def_nn NOT NULL,
comments VARCHAR2(200 CHAR),
CONSTRAINT sc_id_pk PRIMARY KEY (sc_id))';

nCount:=0;--sequence and trigger for primary key
SELECT COUNT(*)
  INTO nCount
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'SC_SEQ';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SC_SEQ';
END IF;

EXECUTE IMMEDIATE 'CREATE SEQUENCE SC_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE';

EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER sc_id_trg
BEFORE INSERT ON sauces
FOR EACH ROW
BEGIN
  IF :new.sc_id IS NULL THEN
    SELECT sc_seq.nextval INTO :new.sc_id FROM dual;
  END IF;
END;';
END;
/
