DECLARE --Аналог CREATE OR REPLACE
nCount NUMBER(1);
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'SAUCES';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE SAUCES CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE SAUCES(
sc_id NUMBER(3),
def VARCHAR2(20) CONSTRAINT def_nn NOT NULL,
comments VARCHAR2(100),
CONSTRAINT sc_id_pk PRIMARY KEY (sc_id))';
END;
/
