--Аналог CREATE OR DROP AND CREATE
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'SAUCES';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE SAUCES';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE SAUCES(
sc_id NUMBER(3),
def VARCHAR2(20),
comments VARCHAR2(100))';
