DECLARE --Аналог CREATE OR REPLACE
nCount NUMBER(1);
BEGIN
SELECT COUNT(*)
  INTO nCount
  FROM USER_TABLES
  WHERE TABLE_NAME = 'SAUCES';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE SAUCES CASCADE CONSTRAINTS';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE SAUCES(
sc_id NUMBER(3),
def VARCHAR2(20) CONSTRAINT def_nn NOT NULL,
comments VARCHAR2(100),
CONSTRAINT sc_id_pk PRIMARY KEY (sc_id))';

nCount:=0;--Обнуляем счетчик. Создаем последовательность и триггер для генерации айдишников
SELECT COUNT(*)
  INTO nCount
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'SC_SEQ';

IF nCount <> 0 THEN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SC_SEQ';
END IF;

EXECUTE IMMEDIATE 'CREATE SEQUENCE SC_SEQ
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE';

EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER sc_id_trg
BEFORE INSERT ON sauces
FOR EACH ROW
BEGIN
  IF :new.sc_id IS NULL THEN
    SELECT sc_seq.nextval INTO :new.sc_id FROM dual;
  END IF;
END;';
END;
/
